website/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^about/$', views.blog_about, name='blog_about'),

]

website/comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
    url(r'^$', views.Home.as_view(), name='url_name_home'),
    url(r'^write/$', views.Write.as_view(), name='write'),
 
]

website/website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^comments/', include('comments.urls')),
]

website/comments/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=20)
    text = models.CharField(max_length=300)
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20] + '...'

class Visit_Comment(models.Model):
    name = models.CharField(max_length=20)
    text = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.text[:20] + '...'

website/comments/forms.py
from django import forms
from .models import Comment,Visit_Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'text']

class Visit_CommentForm(forms.ModelForm):
    class Meta:
        model = Visit_Comment
        fields = ['name', 'text']

website/comments/views.py
# -*- coding: utf-8 -*-
import os
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .models import Comment,Visit_Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 Django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)

    # HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据。
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST 中，这是一个类字典对象。
        # 我们利用这些数据构造了 CommentForm 的实例，这样 Django 的表单就生成了。
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，Django 自动帮我们检查表单的数据是否符合格式要求。
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
            comment = form.save(commit=False)

            # 将评论和被评论的文章关联起来。
            comment.post = post

            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()

            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误。
            # 因此我们传了三个模板变量给 detail.html，
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            # 注意这里我们用到了 post.comment_set.all() 方法，
            # 这个用法有点类似于 Post.objects.all()
            # 其作用是获取这篇 post 下的的全部评论，
            # 因为 Post 和 Comment 是 ForeignKey 关联的，
            # 因此使用 post.comment_set.all() 反向查询全部评论。
            # 具体请看下面的讲解。
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
    return redirect(post)

class Home(ListView):
    model = Visit_Comment
    template_name = 'comments/comment_home.html'
    ordering = ['-date']

class Write(CreateView):
    model = Visit_Comment
    template_name = 'comments/comment_write.html'
    fields = ['text','name']
    success_url = reverse_lazy('comments:url_name_home')

website/templates/comments/comment_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'img/ppawn.jpg' %}">
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta content="email=no" name="format-detection">
    {% block css %}{% endblock %}
    <title>PAWN | 游客留言</title>
</head>
<body>

{% block content %}{% endblock %}

</body>
</html>

website/templates/comments/comment_home.html
{% extends 'comments/comment_base.html' %}
{% load staticfiles %}

{%  block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">


{%  endblock %}

{%  block content %}
<div class="col-xs-7 col-sm-7 col-md-9">

    <div class="col-xs-12 col-sm-12 col-md-12" style="clear:both">
    <div class="media thumbnail mytrans" style="padding: 20px 0;">
    <header class="header">
        <div class="logo">
            <span class="big">游客留言</span>
            <span>1.0</span>
        </div>
        <a href="{% url 'comments:write' %}" class="write">留言</a>
        <a href="{% url 'blog:index' %}" class="write">返回首页</a>
    </header>
    <div class="container">
        <ul>
            {% for post in object_list %}
                <li class="post">
                    <p class="content">{{ post.text }}</p>
                    <p class="name">By {{ post.name }} {{post.date|date:'Y/m/d H:i'}}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

    </div>
    </div>

</div>


{% endblock %}

website/templates/comments/comment_write.html
{% extends 'comments/comment_base.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">
{% endblock %}

{% block content %}
<div class="col-xs-7 col-sm-7 col-md-9">

    <div class="col-xs-12 col-sm-12 col-md-12" style="clear:both">
    <div class="media thumbnail mytrans" style="padding: 20px 0;">
<div class="container" >

    <a href="/comments" class="go-back">返回留言板</a>
    <a href="{% url 'blog:index' %}" class="go-back">返回首页</a>
    <form method="post">
        {% csrf_token %}
        <div class="fieldWrapper" >
            {{ field.errors }} {{ field.label_tag }}
            <label for="id_text">留言昵称：</label>
            {{ form.name }}
            <label for="id_name">留言内容：</label>
            {{ form.text }}
        </div>
        <button type="submit" class="submit" style="margin-top: 20px">发布</button>
    </form>
</div>

    </div>
    </div>
</div>

{% endblock %}