website/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^about/$', views.blog_about, name='blog_about'),

]

website/comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
    url(r'^$', views.Home.as_view(), name='url_name_home'),
    url(r'^write/$', views.Write.as_view(), name='write'),
 
]

website/website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^comments/', include('comments.urls')),
]

website/templates/base.html
{% load staticfiles %}

{% load blog_tags %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>

    <title>{% block title %}{% endblock title %}</title>
    {% block meta %}{% endblock meta %}
    <link rel="shortcut icon" href="{% static 'img/ppawn.jpg' %}">

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">


    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <style>
        span.highlighted {
            color: red;
        }
    </style>

</head>

<body>

{% include 'header.html' %}

{% block main %}{% endblock main %}

{% include 'footer.html' %}

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}" style="font-family: KaiTi;">首页</a></li>
            <li><a href="{% url 'blog:index' %}" style="font-family: KaiTi;">文章随笔</a></li>
            <li><a href="{% url 'blog:blog_about' %}" style="font-family: KaiTi;">关于自己</a></li>
            <li><a href="{% url 'comments:url_name_home' %}" style="font-family: KaiTi;">游客留言</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>

</html>

website/templates/footer.html
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">Copyright © 2018 PAWN. All rights reserved.<br>
                    <a href="http://www.miitbeian.gov.cn/" title="全国备案" target="_blank">粤ICP备18052873号</a>
                </p>
            </div>
        </div>
    </div>
</footer>

website/templates/header.html
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    
                        <h1><a href="/"><img src="/static/img/h.gif" style="width: 50px;height: 50px；margin-top:20px"></a>  <a href="{% url 'blog:index' %}"><b>Pawn</b></a></h1>

                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="margin-top: 5px">
                        <ul class="nav navbar-nav navbar-right" >
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页" style="font-family: KaiTi;">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="文章随笔" style="font-family: KaiTi;">文章随笔</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:blog_about' %}" data-hover="关于自己" style="font-family: KaiTi;">关于自己</a></li>
                            <li class="cl-effect-11"><a href="{% url 'comments:url_name_home' %}" data-hover="游客留言" style="font-family: KaiTi;">游客留言</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>